---
- name: Gather EOS configuration
  eos_command:
    commands: 'show running-config all'
    provider: "{{ provider|default(omit) }}"
    auth_pass: "{{ auth_pass|default(omit) }}"
    authorize: "{{ authorize|default(omit) }}"
    host: "{{ host|default(omit) }}"
    password: "{{ password|default(omit) }}"
    port: "{{ port|default(omit) }}"
    transport: 'cli'
    use_ssl: "{{ use_ssl|default(omit) }}"
    username: "{{ username|default(omit) }}"
  register: output
  no_log: true

- name: Save EOS configuration
  set_fact:
    base_config: "{{ output.result[0] }}"
  no_log: true

- name: Configure Arista EOS Routemaps
  eos_template:
    src: routemaps.j2
    include_defaults: true
    config: "{{ base_config | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    transport: 'cli'
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
  when:
    routemaps is defined and
    item.name|mandatory and
    item.action|mandatory and
    item.seqno|mandatory
  with_items: "{{ routemaps }}"

# - name: Configure Arista EOS Routemaps
#   eos_routemap:
#     name={{ item.name|default(omit) }}
#     action={{ item.action|default(omit) }}
#     seqno={{ item.seqno|default(omit) }}
#     description="{{ item.description|default(omit) }}"
#     set="{{ item.set|default([])|sort(reverse=True)|join(',') or omit }}"
#     match="{{ item.match|default([])|sort|join(',') or omit }}"
#     continue={{ item.continue|default(omit) }}
#     state={{ item.state|default(omit) }}
#     config={{ eos_eapi_config|default(omit) }}
#     username={{ eos_eapi_username|default(omit) }}
#     password={{ eos_eapi_password|default(omit) }}
#     enablepwd={{ eos_eapi_enablepwd|default(omit) }}
#     transport={{ eos_eapi_transport|default(omit) }}
#     connection={{ eos_eapi_connection|default(omit) }}
#     host={{ eos_eapi_host|default(omit) }}
#     port={{ eos_eapi_port|default(omit) }}
#     debug={{ eos_debug|default(omit) }}
#   when: routemaps is defined
#   with_items: routemaps
#
# - name: Configure Arista EOS ACLs
#   eos_acl_entry:
#     name={{ item.name|default(omit) }}
#     action={{ item.action|default(omit) }}
#     seqno={{ item.seqno|default(omit) }}
#     acltype={{ item.type|default(omit) }}
#     srcaddr={{ item.srcaddr|default(omit) }}
#     srcprefixlen={{ item.srcprefixlen|default(omit) }}
#     log={{ item.log|default(omit) }}
#     state={{ item.state|default(omit) }}
#     config={{ eos_eapi_config|default(omit) }}
#     username={{ eos_eapi_username|default(omit) }}
#     password={{ eos_eapi_password|default(omit) }}
#     enablepwd={{ eos_eapi_enablepwd|default(omit) }}
#     transport={{ eos_eapi_transport|default(omit) }}
#     connection={{ eos_eapi_connection|default(omit) }}
#     host={{ eos_eapi_host|default(omit) }}
#     port={{ eos_eapi_port|default(omit) }}
#     debug={{ eos_debug|default(omit) }}
#   when: acls is defined
#   with_items: acls
#
# - name: Configure Arista EOS IPv4 Static Routes
#   eos_staticroute:
#     ip_dest={{ item.ip_dest|default(omit) }}
#     next_hop={{ item.next_hop|default(omit) }}
#     next_hop_ip={{ item.next_hop_ip|default(omit) }}
#     distance={{ item.distance|default(omit) }}
#     route_name={{ item.route_name|default(omit) }}
#     tag={{ item.tag|default(omit) }}
#     state={{ item.state|default(omit) }}
#     config={{ eos_eapi_config|default(omit) }}
#     username={{ eos_eapi_username|default(omit) }}
#     password={{ eos_eapi_password|default(omit) }}
#     enablepwd={{ eos_eapi_enablepwd|default(omit) }}
#     transport={{ eos_eapi_transport|default(omit) }}
#     connection={{ eos_eapi_connection|default(omit) }}
#     host={{ eos_eapi_host|default(omit) }}
#     port={{ eos_eapi_port|default(omit) }}
#     debug={{ eos_debug|default(omit) }}
#   when: ipv4_static_routes is defined
#   with_items: ipv4_static_routes
