# Perform the EOS Routemap tasks under Ansible 2.1 or earlier
# using the Ansible eos_template module

- name: Arista EOS Routemap resources (Ansible <= 2.1)
  eos_template:
    src: routemaps.j2
    include_defaults: true
    config: "{{ _eos_config | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    transport: "{{ transport | default(omit) }}"
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
  notify: save running config
  when:
    item.name is defined and
    item.action is defined and
    item.seqno is defined
  with_items: "{{ routemaps | default([]) }}"

- name: Arista EOS IPv4 Static Route resources (Ansible <= 2.1)
  eos_template:
    src: ipv4_static_routes.j2
    include_defaults: true
    config: "{{ _eos_config | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    transport: "{{ transport | default(omit) }}"
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
  notify: save running config
  when:
    item.ip_dest is defined and
    item.next_hop is defined
  with_items: "{{ ipv4_static_routes | default([]) }}"
